### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by davisjam** [istlab/Alitheia-Core#52]
The README says, "More documentation is always available at the project's web site at http://www.sqo-oss.org".

The website is down.

This makes it hard for me to get started.

**Comment by gousiosg** [comment]
Indeed. Alitheia Core has been retired. Happy to provide some help though.

**Comment by davisjam** [comment]
Hi @gousiosg. I'm not really interested in using a retired project. It might be helpful if you updated the README to indicate the state of the project.
